// Generated by CoffeeScript 2.7.0
(function() {
  var init;

  init = () => {
    return Cube.asyncScramble(function(alg) {
      var puzzle;
      puzzle = TTk.AlgorithmPuzzle(3).alg(alg);
      return puzzle("#puzzle");
    });
  };

  Cube.asyncInit("/cubejs/lib/worker.js", init);

}).call(this);
